from __future__ import annotations

from typing import Iterable

LOCKED_SERIES_OBSERVATIONS: dict[str, list[tuple]] = {
    "Israel": [
        (1975, "National Council for R&D (Israel, pre-1992)", 115000000.0, "unit", "ILP", "1975_Israel.pdf", 16.0, "section_total", "Total"),
        (1976, "National Council for R&D (Israel, pre-1992)", 194100.0, "unit", "ILP", "1976_Israel.pdf", 16.0, "section_total", "Total expenditures"),
        (1977, "National Council for R&D (Israel, pre-1992)", 1000000.0, "unit", "ILP", "1977_Israel.pdf", 55.0, "section_total", "Total"),
        (1978, "National Council for R&D (Israel, pre-1992)", 519286.0, "unit", "ILP", "1978_Israel.pdf", 134.0, "section_total", "Total"),
        (1979, "National Council for R&D (Israel, pre-1992)", 1764000.0, "unit", "ILP", "1979_Israel.pdf", 146.0, "section_total", "Total Expenditures"),
        (1980, "National Council for R&D (Israel, pre-1992)", 604700000.0, "thousand", "ILS_OLD", "1980_Israel.pdf", 97.0, "verified_override", "Verified against original Israel budget file"),
        (1981, "National Council for R&D (Israel, pre-1992)", 1000000000.0, "thousand", "ILS_OLD", "1981_Israel.pdf", 27.0, "verified_override", "Verified against original Israel budget file"),
        (1982, "National Council for R&D (Israel, pre-1992)", 749000000.0, "thousand", "ILS_OLD", "1982_Israel.pdf", 102.0, "verified_override", "Verified against original Israel budget file"),
        (1983, "National Council for R&D (Israel, pre-1992)", 156300000.0, "thousand", "ILS_OLD", "1983_Israel.pdf", 11.0, "verified_override", "Verified against original Israel budget file"),
        (1984, "National Council for R&D (Israel, pre-1992)", 411000000.0, "thousand", "ILS_OLD", "1984_Israel.pdf", 12.0, "verified_override", "Verified against original Israel budget file"),
        (1985, "National Council for R&D (Israel, pre-1992)", 2035.0, "million", "ILS_OLD", "1985_Israel.pdf", 167.0, "section_total", "Total amount"),
        (1986, "National Council for R&D (Israel, pre-1992)", 3708.0, "thousand", "ILS", "1986_Israel.pdf", 180.0, "section_total", "Total"),
        (1986, "Office of the Chief Scientist (Israel, pre-2016)", 486.0, "thousand", "ILS", "1986_Israel.pdf", 216.0, "line_item", "Chief Scientist"),
        (1987, "KAMEA Fund (קרן קמ\"ח)", 3783.0, "thousand", "ILS", "1987_Israel.pdf", 196.0, "line_item", "Research funded by KAMEA"),
        (1987, "National Council for R&D (Israel, pre-1992)", 6400.0, "thousand", "ILS", "1987_Israel.pdf", 146.0, "section_total", "Total amount"),
        (1988, "National Council for R&D (Israel, pre-1992)", 5741.0, "thousand", "ILS", "1988_Israel.pdf", 155.0, "section_total", "Total"),
        (1989, "National Council for R&D (Israel, pre-1992)", 7364.0, "thousand", "ILS", "1989_Israel.pdf", 5.0, "section_total", "Total"),
        (1990, "National Council for R&D (Israel, pre-1992)", 17199.0, "thousand", "ILS", "1990_Israel.pdf", 7.0, "section_total", "Total"),
        (1991, "KAMEA Fund (קרן קמ\"ח)", 3300.0, "thousand", "ILS", "1991_Israel.pdf", 88.0, "line_item", "Research funded by KAMEA"),
        (1991, "National Council for R&D (Israel, pre-1992)", 39503.0, "thousand", "ILS", "1991_Israel.pdf", 133.0, "section_total", "Total"),
        (1992, "Ministry of Science and Technology (Israel)", 21708.0, "thousand", "ILS", "1992_Israel.pdf", 42.0, "section_total", "Total"),
        (1994, "Ministry of Science and Technology (Israel)", 56624.0, "thousand", "ILS", "1994_Israel.pdf", 39.0, "section_total", "Total"),
        (1995, "Israeli Space Agency (סוכנות החלל הישראלית)", 4644.0, "thousand", "ILS", "1995_Israel.pdf", 45.0, "program_total", "Israeli Space Agency"),
        (1995, "Ministry of Science and Technology (Israel)", 152824.0, "thousand", "ILS", "1995_Israel.pdf", 45.0, "section_total", "Total General"),
        (1996, "Ministry of Science and Technology (Israel)", 176579.0, "thousand", "ILS", "1996_Israel.pdf", 44.0, "section_total", "Budget of the Ministry of Science"),
        (1997, "Ministry of Science and Technology (Israel)", 184250.0, "thousand", "ILS", "1997_Israel.pdf", 41.0, "section_total", "Total General"),
        (1998, "Ministry of Science and Technology (Israel)", 825272.0, "thousand", "ILS", "1998_Israel.pdf", 94.0, "section_total", "Total"),
        (1999, "Ministry of Science and Technology (Israel)", 172618.0, "thousand", "ILS", "1999_Israel.pdf", 38.0, "section_total", "Total"),
        (2000, "Ministry of Science and Technology (Israel)", 636117.0, "thousand", "ILS", "2000_Israel.pdf", 36.0, "section_total", "Expenditure"),
        (2001, "Ministry of Science and Technology (Israel)", 722050.0, "thousand", "ILS", "2001_Israel.pdf", 37.0, "section_total", "Total General"),
        (2002, "Ministry of Science and Technology (Israel)", 497804.0, "thousand", "ILS", "2002_Israel.pdf", 41.0, "section_total", "Total"),
        (2004, "Israeli Space Agency (סוכנות החלל הישראלית)", 405.0, "thousand", "ILS", "2004_Israel.pdf", 36.0, "line_item", "Israeli Space Agency"),
        (2004, "Ministry of Science and Technology (Israel)", 118947.0, "thousand", "ILS", "2004_Israel.pdf", 36.0, "section_total", "Total"),
        (2005, "Israeli Space Agency (סוכנות החלל הישראלית)", 15.343, "thousand", "ILS", "2005_Israel.pdf", 36.0, "line_item", "Activities of the Israeli Space Agency"),
        (2005, "Ministry of Science and Technology (Israel)", 118277.0, "thousand", "ILS", "2005_Israel.pdf", 36.0, "section_total", "Total General"),
        (2007, "Israeli Space Agency (סוכנות החלל הישראלית)", 444934.0, "thousand", "ILS", "2007_Israel.pdf", 31.0, "program_total", "Israeli Space Agency"),
        (2007, "Ministry of Science and Technology (Israel)", 700837.0, "thousand", "ILS", "2007_Israel.pdf", 31.0, "section_total", "Total General"),
        (2008, "Ministry of Science and Technology (Israel)", 709529.0, "thousand", "ILS", "2008_Israel.pdf", 29.0, "section_total", "Total General"),
        (2009, "Ministry of Science and Technology (Israel)", 979860.0, "thousand", "ILS", "2009-2010_Israel.pdf", 200.0, "section_total", "Total"),
        (2011, "Israeli Space Agency (סוכנות החלל הישראלית)", 271935.0, "thousand", "ILS", "2011-2012_Israel.pdf", 55.0, "line_item", "Support for Space Agency Activities"),
        (2011, "Ministry of Science and Technology (Israel)", 1400000.0, "thousand", "ILS", "2011-2012_Israel.pdf", 200.0, "verified_override", "Verified against original Israel budget file"),
        (2013, "Ministry of Science and Technology (Israel)", 1117322.0, "thousand", "ILS", "2013-2014_Israel.pdf", 28.0, "verified_override", "Verified against original Israel budget file"),
        (2013, "Office of the Chief Scientist (Israel, pre-2016)", 1684800.0, "thousand", "ILS", "2013-2014_Israel.pdf", 57.0, "program_total", "Chief Scientist"),
        (2015, "Ministry of Science and Technology (Israel)", 1361253.0, "thousand", "ILS", "2015-2016_Israel.pdf", 31.0, "verified_override", "Verified against original Israel budget file"),
        (2017, "Israel Innovation Authority (from 2016)", 175750.0, "thousand", "ILS", "2017-2018_Israel.pdf", 136.0, "line_item", "Operation of the Innovation Authority"),
        (2017, "Ministry of Science and Technology (Israel)", 1573033.0, "thousand", "ILS", "2017-2018_Israel.pdf", 113.0, "section_total", "Total"),
        (2019, "Israeli Space Agency (סוכנות החלל הישראלית)", 874951.0, "thousand", "ILS", "2019_Israel.pdf", 82.0, "program_total", "Budget for the Israeli Space Agency"),
        (2021, "Israeli Space Agency (סוכנות החלל הישראלית)", 561109.0, "thousand", "ILS", "2021_Israel.pdf", 84.0, "line_item", "Budget for the Israeli Space Agency"),
        (2021, "Ministry of Science and Technology (Israel)", 500513.603, "thousand", "ILS", "2021_Israel.pdf", 6.0, "section_total", "Total"),
        (2022, "Israeli Space Agency (סוכנות החלל הישראלית)", 100000.0, "thousand", "ILS", "2022_Israel.pdf", 27.0, "line_item", "Budget for the Israeli Space Agency - Research and Development"),
        (2022, "Ministry of Science and Technology (Israel)", 462500.134, "thousand", "ILS", "2022_Israel.pdf", 6.0, "section_total", "Total budget for the Ministry of Science and Technology"),
        (2023, "Ministry of Science and Technology (Israel)", 2535972.0, "thousand", "ILS", "2023_Israel.pdf", 6.0, "verified_override", "Section 19 total (science + culture bundle)"),
        (2024, "Ministry of Science and Technology (Israel)", 2749765.0, "thousand", "ILS", "2024_Israel.pdf", 6.0, "verified_override", "Section 19 total (science + culture bundle)"),
        (2025, "Israel Innovation Authority (from 2016)", 2008207.0, "thousand", "ILS", "2025_Israel.pdf", 48.0, "verified_override", "Verified against original Israel budget file"),
        (2025, "Ministry of Science and Technology (Israel)", 2807783.0, "thousand", "ILS", "2025_Israel.pdf", 6.0, "verified_override", "Section 19 total (science + culture bundle)"),
    ],
    "Slovenia": [
        (
            2004,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            300_486_000.0,
            "unit",
            "SIT",
            "2004 u2003130.pdf",
            102.0,
            "verified_override",
            "Verified 2004 operating appropriation for Agencija za znanost from the original 2004 budget table (300.486 in v tisoč tolarjih normalized to full SIT units); used as the pre-ARRS science-agency operating bridge",
        ),
        (
            2005,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            309_349_000.0,
            "unit",
            "SIT",
            "2004 u2003130.pdf",
            354.0,
            "verified_override",
            "Verified 2005 operating appropriation for Agencija za znanost from the original 2005 budget table (309.349 in v tisoč tolarjih normalized to full SIT units); used as the pre-ARRS science-agency operating bridge",
        ),
        (
            2006,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            644_689_000.0,
            "unit",
            "SIT",
            "2006 2007 u2005116.pdf",
            112.0,
            "verified_override",
            "Verified 2006 operating appropriation for Delovanje Javne agencije za raziskovalno dejavnost from the original 2006/2007 biennial budget table (644.689 in v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2007,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            2_735_000.0,
            "unit",
            "EUR",
            "2007 RS_-2005-116-05136-OB~P002-0000.pdf",
            105.0,
            "verified_override",
            "Verified 2007 operating appropriation for Delovanje Javne agencije za raziskovalno dejavnost from the original 2006/2007 biennial budget table; the page reports both v 000 SIT and v 000 EUR and the correct annual amount is the EUR column (2.735)",
        ),
        (
            2008,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            3_232_602.0,
            "unit",
            "EUR",
            "2008 2009.pdf",
            116.0,
            "verified_override",
            "Verified 2008 operating appropriation for Delovanje Javne agencije za raziskovalno dejavnost from the original 2008/2009 biennial budget table",
        ),
        (
            2009,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            3_300_902.0,
            "unit",
            "EUR",
            "2009 RS_-2007-114-05699-OB~P002-0000.pdf",
            96.0,
            "verified_override",
            "Verified 2009 operating appropriation for Delovanje Javne agencije za raziskovalno dejavnost from the original 2009 budget table",
        ),
        (
            2011,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            3_198_652.0,
            "unit",
            "EUR",
            "2011 2012 u2010096.pdf",
            49.0,
            "verified_override",
            "Verified 2011 Plan amount for Delovanje ARRS from original 2011/2012 biennial budget table; prior series had taken the full two-year project value instead of the annual plan",
        ),
        (
            2012,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            3_198_652.0,
            "unit",
            "EUR",
            "2012 RS_-2010-096-05013-OB~P003-0000.pdf",
            10.0,
            "verified_override",
            "Verified 2012 Plan amount for Delovanje ARRS from original 2012 budget table; prior series had taken the full two-year project value instead of the annual plan",
        ),
        (
            2013,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            2_700_000.0,
            "unit",
            "EUR",
            "2013 u2012104.pdf",
            44.0,
            "verified_override",
            "Verified 2013 Plan amount for Delovanje ARRS from original 2013/2014 biennial budget table; source page shows the annual operating appropriation on line 3211-11-0026",
        ),
        (
            2015,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            2_700_000.0,
            "unit",
            "EUR",
            "2015 RS_-2013-102-03719-OB~P003-0000.pdf",
            13.0,
            "verified_override",
            "Verified 2015 Plan amount for Delovanje ARRS from original 2015 budget table",
        ),
        (
            2016,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            2_959_267.0,
            "unit",
            "EUR",
            "2016 u2015096.pdf",
            42.0,
            "verified_override",
            "Verified 2016 Plan amount for Delovanje ARRS from original 2016 project table; prior selection had taken the full project value instead of the annual plan",
        ),
        (
            2017,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            2_970_469.0,
            "unit",
            "EUR",
            "2017 u2016080.pdf",
            45.0,
            "verified_override",
            "Verified 2017 Plan amount for Delovanje ARRS from original 2017 budget table",
        ),
        (
            2018,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            3_595_469.0,
            "unit",
            "EUR",
            "2018 u2017071.pdf",
            46.0,
            "verified_override",
            "Verified 2018 Plan amount for Delovanje ARRS from original 2018 budget table",
        ),
        (
            2019,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            3_648_196.0,
            "unit",
            "EUR",
            "2018 u2017071.pdf",
            240.0,
            "verified_override",
            "Verified 2019 Plan amount for Delovanje ARRS from original 2018/2019 biennial budget table",
        ),
        (
            2020,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            3_910_054.0,
            "unit",
            "EUR",
            "2020 u2019075.pdf",
            54.0,
            "verified_override",
            "Verified 2020 Plan amount for Delovanje ARRS from original 2020 budget table",
        ),
        (
            2021,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            3_915_427.0,
            "unit",
            "EUR",
            "2021 u2020174.pdf",
            56.0,
            "verified_override",
            "Verified 2021 Plan amount for Delovanje ARRS from original 2021 budget table",
        ),
        (
            2022,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            4_500_000.0,
            "unit",
            "EUR",
            "2022 u2021187.pdf",
            53.0,
            "verified_override",
            "Verified 2022 Plan amount for Delovanje ARRS from original 2022 budget table; prior override had accidentally taken the 2023 column from a later page in the same biennial file",
        ),
        (
            2023,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            5_629_258.0,
            "unit",
            "EUR",
            "2023 u2022150.pdf",
            56.0,
            "verified_override",
            "Verified 2023 Plan amount for Delovanje ARRS from original 2023 budget table",
        ),
        (
            2024,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            6_935_000.0,
            "unit",
            "EUR",
            "2024 u2023123.pdf",
            51.0,
            "verified_override",
            "Verified 2024 Plan amount for Delovanje ARIS from original 2024 budget table; this is the agency operating appropriation, not the PPUD sub-line that earlier filtering had dropped",
        ),
        (
            2025,
            "ARRS — Agencija za raziskovalno dejavnost Republike Slovenije",
            9_430_012.0,
            "unit",
            "EUR",
            "2025 u2024104.pdf",
            55.0,
            "verified_override",
            "Verified 2025 Plan amount for Delovanje ARIS from original 2025 budget table; this is the agency operating appropriation, not the PPUD sub-line that earlier filtering had dropped",
        ),
        (
            2001,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            24_274_766_000.0,
            "unit",
            "SIT",
            "2001 u2001032.pdf",
            100.0,
            "verified_override",
            "Verified 2001 Programme 0502 total from original 2001 budget table (v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2002,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            26_788_695_000.0,
            "unit",
            "SIT",
            "2002 u2001103.pdf",
            100.0,
            "verified_override",
            "Verified 2002 Programme 0502 total from original 2002 budget table (v tisoč tolarjih normalized to full SIT units); replaced later-year carryover selection from the same file",
        ),
        (
            2003,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            28_821_059_000.0,
            "unit",
            "SIT",
            "2003 u2002118.pdf",
            101.0,
            "verified_override",
            "Verified 2003 Programme 0502 total from original 2003 budget table (v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2004,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            31_399_927_000.0,
            "unit",
            "SIT",
            "2004 u2003130.pdf",
            102.0,
            "verified_override",
            "Verified 2004 Programme 0502 total from original 2004 budget file (v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2005,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            32_080_394_000.0,
            "unit",
            "SIT",
            "2004 u2003130.pdf",
            354.0,
            "verified_override",
            "Verified 2005 Programme 0502 total from original 2005 budget table (v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2006,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            34_480_096_000.0,
            "unit",
            "SIT",
            "2006 2007 u2005116.pdf",
            415.0,
            "verified_override",
            "Verified 2006 Programme 0502 total from original 2006/2007 biennial budget table (v 000 SIT normalized to full SIT units)",
        ),
        (
            2007,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            143_883_000.0,
            "unit",
            "EUR",
            "2007 RS_-2005-116-05136-OB~P002-0000.pdf",
            105.0,
            "verified_override",
            "Verified 2007 Programme 0502 total from original 2006/2007 biennial budget table; the page reports both v 000 SIT and v 000 EUR, and the correct 2007 amount is the EUR column (143.883) rather than the SIT carryover column (34.480.096)",
        ),
        (
            2008,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            37_254_650.0,
            "unit",
            "EUR",
            "2008 2009.pdf",
            285.0,
            "verified_override",
            "Verified 2008 Programme 0502 total from original 2008/2009 biennial budget table; the correct value is the Plan 2008 column (37.254.650), and earlier series had drifted to the Plan 2009 column / nearby 05023201 subline",
        ),
        (
            2009,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            173_531_954.0,
            "unit",
            "EUR",
            "2009 RS_-2007-114-05699-OB~P002-0000.pdf",
            96.0,
            "verified_override",
            "Verified 2009 Programme 0502 total from original 2009 budget table",
        ),
        (
            2010,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            191_826_216.0,
            "unit",
            "EUR",
            "2010 u2009099.pdf",
            159.0,
            "verified_override",
            "Verified 2010 Programme 0502 total from original 2010 budget summary page",
        ),
        (
            2011,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            226_692_429.0,
            "unit",
            "EUR",
            "2011 2012 u2010096.pdf",
            48.0,
            "verified_override",
            "Verified 2011 Programme 0502 total from original 2011/2012 biennial budget table; prior series had mistakenly taken the multi-year cumulative total instead of the current-year column",
        ),
        (
            2012,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            203_661_079.0,
            "unit",
            "EUR",
            "2012 RS_-2010-096-05013-OB~P002-0000.pdf",
            17.0,
            "verified_override",
            "Verified 2012 Programme 0502 total from original 2012 budget summary page",
        ),
        (
            2013,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            167_976_945.0,
            "unit",
            "EUR",
            "2013 u2012104.pdf",
            43.0,
            "verified_override",
            "Verified 2013 Programme 0502 total from original 2013 budget table",
        ),
        (
            2015,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            135_558_193.0,
            "unit",
            "EUR",
            "2015 RS_-2013-102-03719-OB~P002-0000.pdf",
            13.0,
            "verified_override",
            "Verified 2015 Programme 0502 total from original 2015 budget table",
        ),
        (
            2016,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            188_104_677.0,
            "unit",
            "EUR",
            "2016 u2015096.pdf",
            203.0,
            "verified_override",
            "Verified 2016 Programme 0502 total from original 2016 budget table",
        ),
        (
            2017,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            215_666_722.0,
            "unit",
            "EUR",
            "2017 u2016080.pdf",
            44.0,
            "verified_override",
            "Verified 2017 Programme 0502 total from original 2017 budget table",
        ),
        (
            2018,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            242_949_117.0,
            "unit",
            "EUR",
            "2018 2019 u2017071.pdf",
            44.0,
            "verified_override",
            "Verified 2018 Programme 0502 total from original 2018 budget table; prior series had incorrectly duplicated the 2019 total from the later page in the same biennial file",
        ),
        (
            2019,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            249_002_396.0,
            "unit",
            "EUR",
            "2019 RS_-2017-071-03414-OB~P003-0000.pdf",
            15.0,
            "verified_override",
            "Verified 2019 Programme 0502 total from original 2019 budget table",
        ),
        (
            2020,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            306_498_850.0,
            "unit",
            "EUR",
            "2020 u2019075.pdf",
            51.0,
            "verified_override",
            "Verified 2020 Programme 0502 total from original 2020 budget table; prior series had taken the 050201 subprogramme instead of the full 0502 total",
        ),
        (
            2021,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            327_188_033.0,
            "unit",
            "EUR",
            "2021 u2020174.pdf",
            51.0,
            "verified_override",
            "Verified 2021 Programme 0502 total from original 2021 budget table",
        ),
        (
            2022,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            364_075_611.0,
            "unit",
            "EUR",
            "2022 u2021187.pdf",
            49.0,
            "verified_override",
            "Verified 2022 Programme 0502 total from original 2022 budget table; prior series had taken the 050201 subprogramme instead of the full 0502 total",
        ),
        (
            2023,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            389_895_145.0,
            "unit",
            "EUR",
            "2023 u2022150.pdf",
            53.0,
            "verified_override",
            "Verified 2023 Programme 0502 total from original 2023 budget table",
        ),
        (
            2024,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            407_736_802.0,
            "unit",
            "EUR",
            "2024 u2023123.pdf",
            47.0,
            "verified_override",
            "Verified 2024 Programme 0502 total from original 2024 budget table; corrected source page to the Plan 2024 detailed table instead of the later Plan 2025 page in the same biennial file",
        ),
        (
            2025,
            "Programme 0502 — Znanstveno raziskovalna dejavnost",
            465_702_894.0,
            "unit",
            "EUR",
            "2025 u2024104.pdf",
            51.0,
            "verified_override",
            "Verified 2025 Programme 0502 total from original 2025 budget table; prior series had taken the 050201 subprogramme instead of the full 0502 total",
        ),
        (
            2002,
            "Programme 0503 — Mladi raziskovalci / Človeški viri v podporo znanosti",
            95_000_000.0,
            "unit",
            "SIT",
            "2002 u2001103.pdf",
            171.0,
            "verified_override",
            "Verified 2002 amount for Programi za mlade raziskovalce from original 2002 budget table (95.000 in v tisoč SIT)",
        ),
        (
            2019,
            "Programme 0503 — Mladi raziskovalci / Človeški viri v podporo znanosti",
            170_000.0,
            "unit",
            "EUR",
            "2019 RS_-2017-071-03414-OB~P003-0000.pdf",
            17.0,
            "verified_override",
            "Verified 2019 amount for 050302 Mladi raziskovalci, mobilnost in spodbude najboljsim raziskovalcem from original 2019 budget table",
        ),
        (
            2020,
            "Programme 0503 — Mladi raziskovalci / Človeški viri v podporo znanosti",
            210_000.0,
            "unit",
            "EUR",
            "2020 u2019075.pdf",
            55.0,
            "verified_override",
            "Verified 2020 amount for 050302 Mladi raziskovalci, mobilnost in spodbude najboljsim raziskovalcem from original 2020 budget table",
        ),
        (
            2021,
            "Programme 0503 — Mladi raziskovalci / Človeški viri v podporo znanosti",
            210_000.0,
            "unit",
            "EUR",
            "2021 u2020174.pdf",
            57.0,
            "verified_override",
            "Verified 2021 amount for 050302 Mladi raziskovalci, mobilnost in spodbude najboljsim raziskovalcem from original 2021 budget table",
        ),
        (
            2022,
            "Programme 0503 — Mladi raziskovalci / Človeški viri v podporo znanosti",
            310_000.0,
            "unit",
            "EUR",
            "2022 u2021187.pdf",
            54.0,
            "verified_override",
            "Verified 2022 amount for 050302 Young researchers, mobility and incentives for the best researchers from original 2022 budget table",
        ),
        (
            2023,
            "Programme 0503 — Mladi raziskovalci / Človeški viri v podporo znanosti",
            350_000.0,
            "unit",
            "EUR",
            "2023 u2022150.pdf",
            57.0,
            "verified_override",
            "Verified 2023 amount for 050302 Mladi raziskovalci, mobilnost in spodbude najboljsim raziskovalcem from original 2023 budget table",
        ),
        (
            2024,
            "Programme 0503 — Mladi raziskovalci / Človeški viri v podporo znanosti",
            390_000.0,
            "unit",
            "EUR",
            "2024 u2023123.pdf",
            51.0,
            "verified_override",
            "Verified 2024 amount for 050302 Mladi raziskovalci, mobilnost in spodbude najboljsim raziskovalcem from original 2024/2025 biennial budget table; source page shows 390.000 for Plan 2024 and 450.000 for Plan 2025, but the separate 2025 budget no longer carries a surviving 050302 line",
        ),
        (
            2023,
            "European Space Agency Programs",
            5_400_000.0,
            "unit",
            "EUR",
            "2023 u2022150.pdf",
            192.0,
            "verified_override",
            "Verified 2023 amount for Programi Evropske vesoljske agencije from original 2023/2024 biennial budget table; source page is headed Plan 2023/2024/2025/2026 and the ESA project line shows 5.400.000 for Plan 2023",
        ),
        (
            2024,
            "European Space Agency Programs",
            6_300_000.0,
            "unit",
            "EUR",
            "2024 u2023123.pdf",
            155.0,
            "verified_override",
            "Verified 2024 amount for Programi Evropske vesoljske agencije from original 2024/2025 biennial budget table",
        ),
        (
            2025,
            "European Space Agency Programs",
            7_361_400.0,
            "unit",
            "EUR",
            "2025 u2024104.pdf",
            162.0,
            "verified_override",
            "Verified 2025 amount for Programi Evropske vesoljske agencije from original 2025 budget table",
        ),
        (
            2024,
            "Development of Research and Innovation Capacities",
            121_043_968.0,
            "unit",
            "EUR",
            "2024 u2023123.pdf",
            51.0,
            "verified_override",
            "Verified 2024 amount for Razvoj raziskovalne in inovacijske zmogljivosti from original 2024/2025 biennial budget table; source places the series under 0504/050401 rather than 0502",
        ),
        (
            2025,
            "Development of Research and Innovation Capacities",
            53_477_326.0,
            "unit",
            "EUR",
            "2025 u2024104.pdf",
            56.0,
            "verified_override",
            "Verified 2025 amount for Razvoj raziskovalne in inovacijske zmogljivosti from original 2025 budget table; source places the series under 0504/050401 rather than 0502",
        ),
        (
            1992,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            77_763_150.0,
            "unit",
            "SIT",
            "1992 u1992016.pdf",
            123.0,
            "verified_override",
            "Verified 1992 SAZU institution total from original 1992 budget table (explicit institution total on source page)",
        ),
        (
            1993,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            180_586_876.0,
            "unit",
            "SIT",
            "1993 u1993022.pdf",
            104.0,
            "verified_override",
            "Verified 1993 SAZU institution total from original scanned 1993 budget page; source page explicitly reports 'Skupaj organ # 39' for SAZU as 180.586.876,00 in full SIT units",
        ),
        (
            1994,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            195_214_000.0,
            "unit",
            "SIT",
            "1994 u1994026.pdf",
            91.0,
            "verified_override",
            "Verified 1994 SAZU institution total from original 1994 budget table (v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            1995,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            447_163_000.0,
            "unit",
            "SIT",
            "1995 u1995040.pdf",
            93.0,
            "verified_override",
            "Verified 1995 SAZU institution total from original scanned 1995 budget page (447.163 in v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            1996,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            492_970_000.0,
            "unit",
            "SIT",
            "1996 u1996005.pdf",
            94.0,
            "verified_override",
            "Verified 1996 SAZU institution total from original 1996 budget table (v tisoč tolarjih normalized to full SIT units); replaced a sub-line capture with the full institution total",
        ),
        (
            1997,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            459_528_000.0,
            "unit",
            "SIT",
            "1997 u1997078.pdf",
            108.0,
            "verified_override",
            "Verified 1997 SAZU institution total from original 1997 budget table (v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            1998,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            625_146_000.0,
            "unit",
            "SIT",
            "1998 u1998034.pdf",
            116.0,
            "verified_override",
            "Verified 1998 SAZU institution total from original 1998 budget table (v 000 tolarjih normalized to full SIT units); replaced a sub-line capture with the full institution total",
        ),
        (
            1999,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            663_021_000.0,
            "unit",
            "SIT",
            "1999 u1998091.pdf",
            319.0,
            "verified_override",
            "Verified 1999 SAZU institution total from original 1999 budget table (v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2000,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            687_310_000.0,
            "unit",
            "SIT",
            "2000 u2000009.pdf",
            27.0,
            "verified_override",
            "Verified 2000 SAZU institution total from original 2000 budget table (v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2001,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            665_229_000.0,
            "unit",
            "SIT",
            "2001 u2001032.pdf",
            18.0,
            "verified_override",
            "Verified 2001 SAZU institution total from original 2001 budget table (v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2002,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            770_612_000.0,
            "unit",
            "SIT",
            "2002 u2001103.pdf",
            242.0,
            "verified_override",
            "Verified 2002 SAZU institution total from original 2002 budget table (v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2003,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            767_787_000.0,
            "unit",
            "SIT",
            "2003 u2002118.pdf",
            18.0,
            "verified_override",
            "Verified 2003 SAZU institution total from original 2003 budget table (v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2004,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            859_147_000.0,
            "unit",
            "SIT",
            "2004 u2003130.pdf",
            17.0,
            "verified_override",
            "Verified 2004 SAZU institution total from original 2004 budget table (859.147 in v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2005,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            929_948_000.0,
            "unit",
            "SIT",
            "2005 RS_-2003-130-05511-OB~P001-0000.pdf",
            17.0,
            "verified_override",
            "Verified 2005 SAZU institution total from original 2005 budget table (v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2006,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            941_790_000.0,
            "unit",
            "SIT",
            "2006 2007 u2005116.pdf",
            19.0,
            "verified_override",
            "Verified 2006 SAZU institution total from original 2006/2007 biennial budget table (941.790 in v tisoč tolarjih normalized to full SIT units)",
        ),
        (
            2007,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            3_964_000.0,
            "unit",
            "EUR",
            "2007 RS_-2005-116-05136-OB~P002-0000.pdf",
            11.0,
            "verified_override",
            "Verified 2007 SAZU institution total from original 2006/2007 biennial budget table; page reports both v 000 SIT and v 000 EUR, and the correct annual amount is the EUR column (3.964)",
        ),
        (
            2008,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            3_898_134.0,
            "unit",
            "EUR",
            "2008 2009.pdf",
            18.0,
            "verified_override",
            "Verified 2008 SAZU institution total from original 2008/2009 biennial budget table",
        ),
        (
            2009,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            3_898_708.0,
            "unit",
            "EUR",
            "2009 RS_-2007-114-05699-OB~P002-0000.pdf",
            11.0,
            "verified_override",
            "Verified 2009 SAZU institution total from original 2009 budget table",
        ),
        (
            2010,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            4_201_406.0,
            "unit",
            "EUR",
            "2010 u2009099.pdf",
            9.0,
            "verified_override",
            "Verified 2010 SAZU institution total from original 2010 budget summary page",
        ),
        (
            2013,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            3_543_692.0,
            "unit",
            "EUR",
            "2013 u2012104.pdf",
            10.0,
            "verified_override",
            "Verified 2013 SAZU institution total from original 2013 budget summary page",
        ),
        (
            2015,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            3_300_044.0,
            "unit",
            "EUR",
            "2015 RS_-2013-102-03719-OB~P002-0000.pdf",
            2.0,
            "verified_override",
            "Verified 2015 SAZU institution total from original 2015 budget summary page",
        ),
        (
            2016,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            2_818_969.0,
            "unit",
            "EUR",
            "2016 u2015096.pdf",
            9.0,
            "verified_override",
            "Verified 2016 SAZU institution total from original 2016 budget summary page",
        ),
        (
            2017,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            2_883_932.0,
            "unit",
            "EUR",
            "2017 u2016080.pdf",
            9.0,
            "verified_override",
            "Verified 2017 SAZU institution total from original 2017 budget summary page",
        ),
        (
            2018,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            2_989_899.0,
            "unit",
            "EUR",
            "2018 2019 u2017071.pdf",
            9.0,
            "verified_override",
            "Verified 2018 SAZU institution total from original 2018 budget summary page; replaced a mixed subprogramme capture with the full institution total",
        ),
        (
            2019,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            3_080_248.0,
            "unit",
            "EUR",
            "2019 RS_-2017-071-03414-OB~P002-0000.pdf",
            2.0,
            "verified_override",
            "Verified 2019 SAZU institution total from original 2019 budget summary page; replaced a mixed subprogramme capture with the full institution total",
        ),
        (
            2020,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            3_678_427.0,
            "unit",
            "EUR",
            "2020 u2019075.pdf",
            9.0,
            "verified_override",
            "Verified 2020 SAZU institution total from original 2020 budget summary page",
        ),
        (
            2021,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            3_774_627.0,
            "unit",
            "EUR",
            "2021 u2020174.pdf",
            9.0,
            "verified_override",
            "Verified 2021 SAZU institution total from original 2021 budget summary page",
        ),
        (
            2022,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            3_793_627.0,
            "unit",
            "EUR",
            "2021 u2020174.pdf",
            238.0,
            "verified_override",
            "Verified 2022 SAZU institution total from original 2022 budget summary page",
        ),
        (
            2023,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            4_120_000.0,
            "unit",
            "EUR",
            "2023 u2022150.pdf",
            9.0,
            "verified_override",
            "Verified 2023 SAZU institution total from original 2023 budget summary page",
        ),
        (
            2024,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            3_746_598.0,
            "unit",
            "EUR",
            "2024 u2023123.pdf",
            9.0,
            "verified_override",
            "Verified 2024 SAZU institution total from original 2024 budget summary page",
        ),
        (
            2025,
            "SAZU — Slovenska akademija znanosti in umetnosti",
            4_569_580.0,
            "unit",
            "EUR",
            "2025 u2024104.pdf",
            10.0,
            "verified_override",
            "Verified 2025 SAZU institution total from original 2025 budget summary page; replaced an incorrect later-year page capture",
        ),
    ],
    "Slovakia": [
        (
            2025,
            "Ministerstvo školstva SR (kapitola 20)",
            5_358_963_927.0,
            "euro",
            "EUR",
            "2025 20250101_5681740-2.pdf",
            1.0,
            "verified_override",
            "Verified against original 2025 budget table: the ministry chapter total is 5,358,963,927 EUR; prior extraction had incorrectly picked 672,888 from a secondary column",
        ),
    ],
    "Luxembourg": [
        (
            2001,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            5_000_000.0,
            "euro",
            "EUR",
            "2001 eli-etat-leg-memorial-2000-a140-fr-pdf.pdf",
            70.0,
            "verified_override",
            "Verified 2001 FNR appropriation from section 03.5 'Recherche scientifique et recherche appliquée' in the original budget page",
        ),
        (
            2002,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            7_500_000.0,
            "euro",
            "EUR",
            "2002 eli-etat-leg-memorial-2001-a148-fr-pdf.pdf",
            66.0,
            "verified_override",
            "Verified 2002 FNR appropriation from section 03.5 'Recherche scientifique et recherche appliquée' in the original budget page",
        ),
        (
            2004,
            "Université du Luxembourg",
            20_391_507.0,
            "euro",
            "EUR",
            "2004 eli-etat-leg-memorial-2003-a184-fr-pdf.pdf",
            80.0,
            "verified_override",
            "Verified 2004 core University of Luxembourg state contribution from section 03.6 in the original budget page",
        ),
        (
            2004,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            11_165_000.0,
            "euro",
            "EUR",
            "2004 eli-etat-leg-memorial-2003-a184-fr-pdf.pdf",
            80.0,
            "verified_override",
            "Verified 2004 FNR appropriation from section 03.5 'Recherche scientifique et recherche appliquée' in the original budget page",
        ),
        (
            2006,
            "Université du Luxembourg",
            44_054_340.0,
            "euro",
            "EUR",
            "2006 eli-etat-leg-memorial-2005-a217-fr-pdf.pdf",
            85.0,
            "verified_override",
            "Verified 2006 core University of Luxembourg state contribution from section 03.6 in the original budget page",
        ),
        (
            2003,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            7_833_900.0,
            "euro",
            "EUR",
            "2003 eli-etat-leg-memorial-2002-a143-fr-pdf.pdf",
            75.0,
            "verified_override",
            "Verified 2003 FNR appropriation from section 03.5 'Recherche scientifique et recherche appliquée' in the original budget page",
        ),
        (
            2005,
            "Université du Luxembourg",
            31_238_340.0,
            "euro",
            "EUR",
            "2005 eli-etat-leg-memorial-2004-a204-fr-pdf.pdf",
            72.0,
            "verified_override",
            "Verified 2005 core University of Luxembourg state contribution from section 03.6 in the original budget page",
        ),
        (
            2005,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            13_090_000.0,
            "euro",
            "EUR",
            "2005 eli-etat-leg-memorial-2004-a204-fr-pdf.pdf",
            72.0,
            "verified_override",
            "Verified 2005 FNR appropriation from section 03.5 'Recherche scientifique et recherche appliquée' in the original budget page",
        ),
        (
            2005,
            "LISER / CEPS-INSTEAD (Luxembourg)",
            4_920_000.0,
            "euro",
            "EUR",
            "2005 eli-etat-leg-memorial-2004-a204-fr-pdf.pdf",
            72.0,
            "verified_override",
            "Verified 2005 CEPS socio-economic research appropriation from section 03.5 'Recherche scientifique et recherche appliquée' in the original budget page",
        ),
        (
            2006,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            14_500_000.0,
            "euro",
            "EUR",
            "2006 eli-etat-leg-memorial-2005-a217-fr-pdf.pdf",
            85.0,
            "verified_override",
            "Verified 2006 FNR appropriation from section 03.5 'Recherche et innovation' in the original budget page",
        ),
        (
            2006,
            "LISER / CEPS-INSTEAD (Luxembourg)",
            5_265_000.0,
            "euro",
            "EUR",
            "2006 eli-etat-leg-memorial-2005-a217-fr-pdf.pdf",
            85.0,
            "verified_override",
            "Verified 2006 CEPS socio-economic research appropriation from section 03.5 'Recherche et innovation' in the original budget page",
        ),
        (
            2007,
            "Université du Luxembourg",
            48_500_000.0,
            "euro",
            "EUR",
            "2007 eli-etat-leg-memorial-2006-a236-fr-pdf.pdf",
            83.0,
            "verified_override",
            "Verified 2007 core University of Luxembourg state contribution from section 03.6 in the original budget page",
        ),
        (
            2007,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            18_000_000.0,
            "euro",
            "EUR",
            "2007 eli-etat-leg-memorial-2006-a236-fr-pdf.pdf",
            82.0,
            "verified_override",
            "Verified 2007 FNR appropriation from section 03.5 'Recherche et innovation' in the original budget page",
        ),
        (
            2007,
            "LISER / CEPS-INSTEAD (Luxembourg)",
            6_500_000.0,
            "euro",
            "EUR",
            "2007 eli-etat-leg-memorial-2006-a236-fr-pdf.pdf",
            83.0,
            "verified_override",
            "Verified 2007 CEPS socio-economic research appropriation from section 03.5 'Recherche et innovation' in the original budget page",
        ),
        (
            2008,
            "Université du Luxembourg",
            58_000_000.0,
            "euro",
            "EUR",
            "2008 eli-etat-leg-memorial-2007-a236-fr-pdf.pdf",
            76.0,
            "verified_override",
            "Verified 2008 core University of Luxembourg state contribution from section 03.6 in the original budget page",
        ),
        (
            2008,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            22_360_000.0,
            "euro",
            "EUR",
            "2008 eli-etat-leg-memorial-2007-a236-fr-pdf.pdf",
            75.0,
            "verified_override",
            "Verified 2008 FNR appropriation from section 03.5 'Recherche et innovation' in the original budget page",
        ),
        (
            2008,
            "CRP Gabriel Lippmann (Luxembourg)",
            15_400_000.0,
            "euro",
            "EUR",
            "2008 eli-etat-leg-memorial-2007-a236-fr-pdf.pdf",
            75.0,
            "verified_override",
            "Verified 2008 CRP Gabriel Lippmann appropriation from section 03.5 'Recherche et innovation' in the original budget page",
        ),
        (
            2008,
            "LIST / CRP Henri Tudor (Luxembourg)",
            17_900_000.0,
            "euro",
            "EUR",
            "2008 eli-etat-leg-memorial-2007-a236-fr-pdf.pdf",
            75.0,
            "verified_override",
            "Verified 2008 CRP Henri Tudor appropriation from section 03.5 'Recherche et innovation' in the original budget page",
        ),
        (
            2008,
            "LIH / CRP Santé (Luxembourg)",
            15_500_000.0,
            "euro",
            "EUR",
            "2008 eli-etat-leg-memorial-2007-a236-fr-pdf.pdf",
            75.0,
            "verified_override",
            "Verified 2008 CRP Santé appropriation from section 03.5 'Recherche et innovation' in the original budget page",
        ),
        (
            2009,
            "Université du Luxembourg",
            72_000_000.0,
            "euro",
            "EUR",
            "2009 eli-etat-leg-memorial-2008-a200-fr-pdf.pdf",
            77.0,
            "verified_override",
            "Verified 2009 core University of Luxembourg state contribution from section 03.6 in the original budget page",
        ),
        (
            2009,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            28_200_000.0,
            "euro",
            "EUR",
            "2009 eli-etat-leg-memorial-2008-a200-fr-pdf.pdf",
            76.0,
            "verified_override",
            "Verified 2009 FNR appropriation from section 03.5 'Recherche et innovation' in the original budget page",
        ),
        (
            2009,
            "CRP Gabriel Lippmann (Luxembourg)",
            11_300_000.0,
            "euro",
            "EUR",
            "2009 eli-etat-leg-memorial-2008-a200-fr-pdf.pdf",
            77.0,
            "verified_override",
            "Verified 2009 CRP Gabriel Lippmann appropriation from section 03.5 'Recherche et innovation' in the original budget page",
        ),
        (
            2009,
            "LIST / CRP Henri Tudor (Luxembourg)",
            18_900_000.0,
            "euro",
            "EUR",
            "2009 eli-etat-leg-memorial-2008-a200-fr-pdf.pdf",
            77.0,
            "verified_override",
            "Verified 2009 CRP Henri Tudor appropriation from section 03.5 'Recherche et innovation' in the original budget page",
        ),
        (
            2009,
            "LIH / CRP Santé (Luxembourg)",
            16_200_000.0,
            "euro",
            "EUR",
            "2009 eli-etat-leg-memorial-2008-a200-fr-pdf.pdf",
            77.0,
            "verified_override",
            "Verified 2009 CRP Santé appropriation from section 03.5 'Recherche et innovation' in the original budget page",
        ),
        (
            2010,
            "Université du Luxembourg",
            72_000_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2010.pdf",
            79.0,
            "verified_override",
            "Verified 2010 core University of Luxembourg state contribution from section 03.1 in the original budget page",
        ),
        (
            2010,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            40_300_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2010.pdf",
            81.0,
            "verified_override",
            "Verified 2010 FNR appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2010,
            "CRP Gabriel Lippmann (Luxembourg)",
            13_200_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2010.pdf",
            81.0,
            "verified_override",
            "Verified 2010 CRP Gabriel Lippmann appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2010,
            "LIST / CRP Henri Tudor (Luxembourg)",
            20_400_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2010.pdf",
            81.0,
            "verified_override",
            "Verified 2010 CRP Henri Tudor appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2010,
            "LIH / CRP Santé (Luxembourg)",
            19_100_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2010.pdf",
            81.0,
            "verified_override",
            "Verified 2010 CRP Santé core appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2011,
            "Université du Luxembourg",
            87_600_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2011.pdf",
            73.0,
            "verified_override",
            "Verified 2011 core University of Luxembourg state contribution from section 03.1 in the original budget page",
        ),
        (
            2011,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            35_240_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2011.pdf",
            75.0,
            "verified_override",
            "Verified 2011 FNR appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2011,
            "LIST / CRP Henri Tudor (Luxembourg)",
            20_400_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2011.pdf",
            75.0,
            "verified_override",
            "Verified 2011 CRP Henri Tudor appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2011,
            "LIH / CRP Santé (Luxembourg)",
            19_100_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2011.pdf",
            75.0,
            "verified_override",
            "Verified 2011 CRP Santé core appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2011,
            "CRP Gabriel Lippmann (Luxembourg)",
            13_200_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2011.pdf",
            75.0,
            "verified_override",
            "Verified 2011 CRP Gabriel Lippmann appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2012,
            "Université du Luxembourg",
            101_666_674.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2012.pdf",
            70.0,
            "verified_override",
            "Verified 2012 core University of Luxembourg state contribution from section 03.1 in the original budget page",
        ),
        (
            2012,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            45_000_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2012.pdf",
            72.0,
            "verified_override",
            "Verified 2012 FNR appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2012,
            "LIST / CRP Henri Tudor (Luxembourg)",
            22_420_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2012.pdf",
            72.0,
            "verified_override",
            "Verified 2012 CRP Henri Tudor appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2012,
            "LIH / CRP Santé (Luxembourg)",
            21_500_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2012.pdf",
            72.0,
            "verified_override",
            "Verified 2012 CRP Santé core appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2012,
            "CRP Gabriel Lippmann (Luxembourg)",
            15_300_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2012.pdf",
            72.0,
            "verified_override",
            "Verified 2012 CRP Gabriel Lippmann appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2013,
            "Université du Luxembourg",
            114_000_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2013.pdf",
            75.0,
            "verified_override",
            "Verified 2013 core University of Luxembourg state contribution from section 03.1 in the original budget page",
        ),
        (
            2013,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            52_000_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2013.pdf",
            76.0,
            "verified_override",
            "Verified 2013 FNR appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2013,
            "LIST / CRP Henri Tudor (Luxembourg)",
            20_030_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2013.pdf",
            76.0,
            "verified_override",
            "Verified 2013 CRP Henri Tudor appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2013,
            "LIH / CRP Santé (Luxembourg)",
            20_000_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2013.pdf",
            77.0,
            "verified_override",
            "Verified 2013 CRP Santé core appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2013,
            "CRP Gabriel Lippmann (Luxembourg)",
            15_600_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2013.pdf",
            76.0,
            "verified_override",
            "Verified 2013 CRP Gabriel Lippmann appropriation from section 03.2 'Recherche et innovation' in the original budget page",
        ),
        (
            2014,
            "Université du Luxembourg",
            128_694_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2014.pdf",
            78.0,
            "verified_override",
            "Verified 2014 core University of Luxembourg state contribution from section 03.1 in the original budget page",
        ),
        (
            2015,
            "Université du Luxembourg",
            145_435_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2015.pdf",
            78.0,
            "verified_override",
            "Verified 2015 core University of Luxembourg state contribution from section 03.2 in the original budget page",
        ),
        (
            2015,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            60_000_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2015.pdf",
            78.0,
            "verified_override",
            "Verified 2015 FNR appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2015,
            "LISER / CEPS-INSTEAD (Luxembourg)",
            10_500_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2015.pdf",
            78.0,
            "verified_override",
            "Verified 2015 LISER appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2015,
            "LIST / CRP Henri Tudor (Luxembourg)",
            39_000_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2015.pdf",
            79.0,
            "verified_override",
            "Verified 2015 LIST appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2015,
            "LIH / CRP Santé (Luxembourg)",
            31_100_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2015.pdf",
            79.0,
            "verified_override",
            "Verified 2015 LIH appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2016,
            "Université du Luxembourg",
            147_136_500.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2016.pdf",
            77.0,
            "verified_override",
            "Verified 2016 core University of Luxembourg state contribution from section 03.2 in the original budget page",
        ),
        (
            2017,
            "Université du Luxembourg",
            157_467_500.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2017.pdf",
            75.0,
            "verified_override",
            "Verified 2017 core University of Luxembourg state contribution from section 03.2 in the original budget page",
        ),
        (
            2018,
            "Université du Luxembourg",
            156_887_500.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2018.pdf",
            88.0,
            "verified_override",
            "Verified 2018 core University of Luxembourg state contribution from section 03.2 in the original budget page",
        ),
        (
            2019,
            "Université du Luxembourg",
            184_910_000.0,
            "euro",
            "EUR",
            "2019budget-de-l-Etat.pdf",
            85.0,
            "verified_override",
            "Verified 2019 core University of Luxembourg state contribution from section 03.2 in the original budget page",
        ),
        (
            2020,
            "Université du Luxembourg",
            198_130_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2020.pdf",
            81.0,
            "verified_override",
            "Verified 2020 core University of Luxembourg state contribution from section 03.2 in the original budget page",
        ),
        (
            2020,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            66_790_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2020.pdf",
            82.0,
            "verified_override",
            "Verified 2020 FNR appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2020,
            "LISER / CEPS-INSTEAD (Luxembourg)",
            11_990_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2020.pdf",
            82.0,
            "verified_override",
            "Verified 2020 LISER appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2020,
            "LIST / CRP Henri Tudor (Luxembourg)",
            47_770_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2020.pdf",
            82.0,
            "verified_override",
            "Verified 2020 LIST appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2020,
            "LIH / CRP Santé (Luxembourg)",
            38_770_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2020.pdf",
            82.0,
            "verified_override",
            "Verified 2020 LIH appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2021,
            "Université du Luxembourg",
            215_600_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2021.pdf",
            97.0,
            "verified_override",
            "Verified 2021 core University of Luxembourg state contribution from section 03.2 in the original budget page",
        ),
        (
            2021,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            66_830_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2021.pdf",
            98.0,
            "verified_override",
            "Verified 2021 FNR appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2021,
            "LISER / CEPS-INSTEAD (Luxembourg)",
            14_000_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2021.pdf",
            98.0,
            "verified_override",
            "Verified 2021 LISER appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2021,
            "LIST / CRP Henri Tudor (Luxembourg)",
            51_360_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2021.pdf",
            98.0,
            "verified_override",
            "Verified 2021 LIST appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2021,
            "LIH / CRP Santé (Luxembourg)",
            43_260_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2021.pdf",
            98.0,
            "verified_override",
            "Verified 2021 LIH appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2022,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            69_030_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2022.pdf",
            91.0,
            "verified_override",
            "Verified 2022 FNR appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2022,
            "LISER / CEPS-INSTEAD (Luxembourg)",
            14_430_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2022.pdf",
            91.0,
            "verified_override",
            "Verified 2022 LISER appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2022,
            "LIST / CRP Henri Tudor (Luxembourg)",
            52_940_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2022.pdf",
            91.0,
            "verified_override",
            "Verified 2022 LIST appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2022,
            "LIH / CRP Santé (Luxembourg)",
            44_300_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2022.pdf",
            91.0,
            "verified_override",
            "Verified 2022 LIH appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2022,
            "Université du Luxembourg",
            220_670_000.0,
            "euro",
            "EUR",
            "budget-de-l-Etat-2022.pdf",
            91.0,
            "verified_override",
            "Verified 2022 core University of Luxembourg state contribution from section 03.2 in the original budget page",
        ),
        (
            2023,
            "Université du Luxembourg",
            223_950_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2023.pdf",
            89.0,
            "verified_override",
            "Verified 2023 core University of Luxembourg state contribution from section 03.2 in the original budget page",
        ),
        (
            2023,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            70_000_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2023.pdf",
            90.0,
            "verified_override",
            "Verified 2023 FNR appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2023,
            "LISER / CEPS-INSTEAD (Luxembourg)",
            15_210_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2023.pdf",
            90.0,
            "verified_override",
            "Verified 2023 LISER appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2023,
            "LIST / CRP Henri Tudor (Luxembourg)",
            53_970_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2023.pdf",
            90.0,
            "verified_override",
            "Verified 2023 LIST appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2023,
            "LIH / CRP Santé (Luxembourg)",
            44_970_000.0,
            "euro",
            "EUR",
            "budget-de-l-etat-2023.pdf",
            90.0,
            "verified_override",
            "Verified 2023 LIH appropriation from section 03.3 'Recherche et innovation' in the original budget page",
        ),
        (
            2024,
            "Université du Luxembourg",
            238_180_000.0,
            "euro",
            "EUR",
            "budget-de-letat-2024.pdf",
            200.0,
            "verified_override",
            "Verified 2024 core University of Luxembourg state contribution from section 18.2 in the original budget page",
        ),
        (
            2025,
            "FNR — Fonds National de la Recherche (Luxembourg)",
            80_000_000.0,
            "euro",
            "EUR",
            "budget-de-letat-2025.pdf",
            190.0,
            "verified_override",
            "Verified 2025 FNR appropriation from section 16.01 'Recherche et enseignement supérieur' in the original budget page",
        ),
        (
            2025,
            "LISER / CEPS-INSTEAD (Luxembourg)",
            17_190_000.0,
            "euro",
            "EUR",
            "budget-de-letat-2025.pdf",
            190.0,
            "verified_override",
            "Verified 2025 LISER appropriation from section 16.01 'Recherche et enseignement supérieur' in the original budget page",
        ),
        (
            2025,
            "LIST / CRP Henri Tudor (Luxembourg)",
            57_700_000.0,
            "euro",
            "EUR",
            "budget-de-letat-2025.pdf",
            190.0,
            "verified_override",
            "Verified 2025 LIST appropriation from section 16.01 'Recherche et enseignement supérieur' in the original budget page",
        ),
        (
            2025,
            "LIH / CRP Santé (Luxembourg)",
            48_100_000.0,
            "euro",
            "EUR",
            "budget-de-letat-2025.pdf",
            190.0,
            "verified_override",
            "Verified 2025 LIH appropriation from section 16.01 'Recherche et enseignement supérieur' in the original budget page",
        ),
        (
            2025,
            "Université du Luxembourg",
            249_632_000.0,
            "euro",
            "EUR",
            "budget-de-letat-2025.pdf",
            191.0,
            "verified_override",
            "Verified 2025 core University of Luxembourg state contribution from section 16.02 in the original budget page",
        ),
    ],
}


def get_locked_series_entries(country: str) -> list[tuple]:
    return list(LOCKED_SERIES_OBSERVATIONS.get(country, []))


def is_locked_observation(country: str, canonical_name: str, year: int) -> bool:
    entries: Iterable[tuple] = LOCKED_SERIES_OBSERVATIONS.get(country, [])
    return any(int(y) == int(year) and str(cn) == str(canonical_name) for y, cn, *_ in entries)
